project:
  type: website
  output-dir: docs

website:
  title: "Maisie Moline"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    page-layout: full
    css: styles.css

editor: visual

